all:
	cat prsim.rc | /opt/pin-3.2-81205-gcc-linux/pin -ifeellucky -t ../instat.so -- prsim test.prs
	
debug:
	cat prsim.rc | /opt/pin-3.2-81205-gcc-linux/pin -pause_tool 20 -ifeellucky -t ../instat.so -- prsim test.prs

